SELECT
    BOARD.TITLE,
    BOARD.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    SUBSTR(REPLY.CREATED_DATE, 1, 10) AS CREATED_DATE
FROM
    USED_GOODS_BOARD AS BOARD
    JOIN USED_GOODS_REPLY AS REPLY ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE
    BOARD.CREATED_DATE LIKE '2022-10%'
ORDER BY
    REPLY.CREATED_DATE,
    BOARD.TITLE;